### ISSUE TITLE
Generate unique States/Country with full : true

### ISSUE THREAD

**Issue by rasteron** [victorquinn/chancejs#171]
Hey, I'm trying to generate list of all the states with ```full:true``` but this doesn't work..
```
chance.unique(chance.state({ full: true }), 1);
```
Am I missing something or this is not yet supported?

Great script btw

**Comment by oliversalzburg** [comment]
If you just want to list all states that Chance knows, you can use `chance.states()`:

    chance.states().map( function( state ){ return state.name; } );

**Comment by victorquinn** [comment]
Thanks @oliversalzburg for the assist on the answer there!

Also @rasteron if you are trying to generate just the full name of 1 random state as your code snippet seems to imply you can do that with Chance by passing the option after the number to generate. For example:

```js
// Will generate an array with 1 full state name, e.g. ["Nebraska"]
chance.unique(chance.state, 1, { full: true });
```

The first argument to `chance.unique` must be a function, not the result of a function. The problem with your code snippet is that `chance.state({ full: true })` will return a state name `"Nebraska"` which is a string, not a function, so an error is thrown\* because Chance cannot use the string `"Nebraska"` as a function to generate any things, let alone unique things.

\* I notice the error thrown if that first argument is not a function sucks, fixing it now!

Marking this closed as it appears there is no bug here though I will be fixing the crappy error message when the first argument is not a function.

**Comment by rasteron** [comment]
Thanks guys, I got it working now. :+1:

**Comment by oliversalzburg** [comment]
@rasteron If you only want one, why not just use `chance.state( { full : true } )`? Or if it needs to be an array `[ chance.state( { full : true } ) ]`.

Seems a bit lighter than using `chance.unique`.

**Comment by rasteron** [comment]
@oliversalzburg Yes, as I have posted I'm using it to generate a unique random full name states and in a loop. Just tinkering with the library so the ```chance.unique``` solution will do for now.

**Comment by oliversalzburg** [comment]
If you're using that code in a loop, the results are not guaranteed to be unique.

If you know that you'll require 10 unique states throughout the loop, you should generate an array of 10 states with `chance.unique(chance.state, 10, { full: true });` and then use that array in your loop.

In case you were already aware of that, then I'm sorry for being redundant :)

**Comment by rasteron** [comment]
Yep, no worries and thanks again Oliver! :smiley:

**Comment by sadiqhabib** [comment]
Hey is there any way to get something like this ? `chance.address.country({ raw: true })` to get same country's name and its code ?
