### ISSUE TITLE
`chance.exp` doesn't always generate a future date

### ISSUE THREAD

**Issue by pmowrer** [victorquinn/chancejs#186]
~~Both `chance.exp_month` and `chance.exp_year` have `future` flags (for good reason as outlined in the docs). It seems odd that their parent, `chance.exp` doesn't have it. Without it, it's not possible to generate random, **valid** credit card numbers.~~

Looking at the source, there is code which intent is to ensure the generated date is in the future. However, I'm pretty quickly able to generate an exp date that is earlier this year. Not sure why yet, but if I get a chance I'll look into it and PR a fix.

```javascript
> chance.exp({raw: true})
< Object {year: "2015", month: "01"}
```

**Comment by victorquinn** [comment]
Hi @pmowrer `chance.exp` takes care of this for you and always credit card expirations which are valid from the time you create them.

First, only the `chance.exp_month` actually uses the future flag (the docs I just realized are wrong, will fix!).

`chance.exp_year` automatically uses a year in the future.

Further, all the future flag on the ex_month does is specify that the month must be beyond the current month. For example, if it is currently June, it makes sure the month picks from the pool July, August, September, November, December. 

That is only necessary when the expiration year is the current year. For example, January 2015 is invalid as of today because that is in the past. However, for any other year (2016, 2017, 2018, etc.) January is entirely valid.

Here is the current code:

```js
Chance.prototype.exp = function (options) {
        options = initOptions(options);
        var exp = {};

        exp.year = this.exp_year();

        // If the year is this year, need to ensure month is greater than the
        // current month or this expiration will not be valid
        if (exp.year === (new Date().getFullYear())) {
            exp.month = this.exp_month({future: true});
        } else {
            exp.month = this.exp_month();
        }

        return options.raw ? exp : exp.month + '/' + exp.year;
};
```
See how it generates a random expiration year (which is any year from now to 10 years from now) then it checks to see if the year it generated is this year. If so it only generates a month from the current month on. Otherwise it uses the full pool of all 12 months.

Anyway, this is all a very wordy way of saying there is no bug here, this method always generates a valid credit card expiration date in the future.
