### ISSUE TITLE
Using a string as a seed does not produce unique seed values

### ISSUE THREAD

**Issue by dan-tilley** [victorquinn/chancejs#203]
Not sure if this is intended behavior,
but I would expect using values of 'abe' and 'acc' in the constructor to produce different seeds,
currently they do not, see https://jsbin.com/nufeqe/2/edit?js,console

**Comment by oliversalzburg** [comment]
This is a result of how the numeric seed is extracted from a string. The changes between the two strings cancel each other out.

Depending on how much of an impact this has on your code, I would recommend passing the string through a hashing algorithm before passing it into chance.

**Comment by xarvh** [comment]
IIRC, previous docs mentioned that it was possible to use a string as a seed.
If this is not reliable anymore, the constructor should at least throw an exception if the argument type is not something reliable.
The current behavior makes it really hard to debug code.

**Comment by oliversalzburg** [comment]
It *is* valid to use a string as the seed. But some strings will result in the same numerical seed.

The way by which the seed is calculated it rather primitive. If it is *too* primitive for your use case, produce a more complex seed by hashing your input.

That's just my suggestion though :)

**Comment by xarvh** [comment]
So why has the possibility to use a string disappeared from the docs?

**Comment by victorquinn** [comment]
@xarvh I fear you must be mistaken, there was never anything in the docs about using a string as a seed. [Here is the full changelog for the portion on seed](https://github.com/victorquinn/chancejs/commits/gh-pages/usage/_posts/1900-01-01-seed.md) it hasn't been changed since June 2013 when I first wrote it.

However, docs aside [there is a unit test](https://github.com/victorquinn/chancejs/blob/develop/test/test.basic.js#L387) that explicitly tests this case which has consistently passed [since the feature was added in November 2014](https://github.com/victorquinn/chancejs/commit/6a263a3e11b41d4625372a74673ebb1fa9aca4f5).

But, it appears it's a bit too primitive causing collisions with simple strings which is not acceptable.

Working on a fix because I agree it should be able to handle this rather basic case and the current conversion from string to seed is too primitive.

**Comment by dan-tilley** [comment]
Excellent news Victor, I appreciate your work

**Comment by xarvh** [comment]
@victorquinn My mistake. =)

Thanks for your effort, much appreciated.

**Comment by victorquinn** [comment]
Thank you @dan-tilley for the praise and thanks for finding this bug!

**Comment by victorquinn** [comment]
FYI this is live with v0.8.0 on npm now!

The minor version bump was due to the fact that I moved the CLI out [to its own home](https://github.com/victorquinn/chancejs-cli).

I did this:

1. To remove the hard dependency so Chance could be installed with tools like [Jam](http://jamjs.org) which blow up with hard dependencies on non-client-side code.
1. For better separation of concerns, now they're decoupled
