### ISSUE TITLE
Use crypto.getRandomValues for new seeds

### ISSUE THREAD

**Issue by indolering** [victorquinn/chancejs#232]
It's ill advised to use plain `math.random` due to the low entropy available in testing environments.  Instead, use getRandomValues where available (IE11+ `var crypto = window.crypto || window.msCrypto;`).

**Comment by victorquinn** [comment]
This has come up multiple times and my answer is always the same.

First, Chance doesn't use `Math.random()` under the hood to generate its random, by default it uses a [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister). [More info in the docs](http://chancejs.com/#seed)

It does use `Math.random()` by default to pick a seed for the twister if none is provided as the default. This is an important distinction.

This was intentional to provide the ability for "repeatable random" if desired by providing the same [seed](http://chancejs.com/#seed). This is useful for certain use cases (like unit tests where you may want repeatable results).

Second, the rationale for not using any specific crypto library under the hood was that Chance was built to work almost anywhere. It will currently run in practically any Browser or [Node.js](https://nodejs.org/), in [Mongo](https://docs.mongodb.org/manual/core/server-side-javascript/), in [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino). I've even had people email me about successfully cross-compiling Chance to Java and other languages.

I've ensured this is the case by having zero dependencies, using only vanilla JS (es5), and by not depending on any specific crypto implementations (e.g. `window.crypto` or [Node's crypto](https://nodejs.org/api/crypto.html#crypto_crypto))

If Chance instead used what you suggest (`window.crypto`) that limits functionality only to the browser (breaking all server-side implementations along with cross compilation), and further only to browsers that support crypto (which is admittedly becoming more prevalent but still not yet universal).

However, I anticipated this from Chance's humble start a few years back, so [back in 2013](https://github.com/victorquinn/chancejs/commit/3ed5a5a44ea1a55430b4fb5d9554ffffbba43c5d) I wrote into Chance the ability to specify an arbitrary random function of your choosing so a developer could override the default and use any method for the random number generator underlying Chance. This provides optimal flexibility. 

You can simply specify the function you'd like to use as a random number generator (any function which returns a number from 0 to 1) and Chance will use your method instead of its Mersenne Twister. [See the docs here.](http://chancejs.com/#function)

So if you'd like to specify `window.crypto` for your particular application rather than the Mersenne Twister, the following snippet will do it for you:

```js
var chance = new Chance(function() {
    var arr = new Uint32Array(1);
    window.crypto.getRandomValues(arr);
    // This jazz is necessary to translate from a random integer to a floating point from 0 to 1
    return arr[0]/(0xffffffff + 1);
});
// Now chance will use window.crypto for random rather than the Mersenne Twister
```

This will get you the results you'd like without limiting compatibility and without dropping the feature of being able to provide a seed and get repeatable random.

Given that not using `window.crypto` is a feature, not a bug, I am closing this issue.

**Comment by indolering** [comment]
> This has come up multiple times and my answer is always the same.

My apologies, I searched through the issue tickets before posting and I noticed a note on the website about using a truly random source:

>There is nothing that would prevent this library from choosing, on instantiation, another random underbase though so in theory this whole library could work with a “true” random base.

I took this to mean that you would like to improve the source for your random seed for situations in which true randomness was desired. 

> First, Chance doesn't use `Math.random()` under the hood to generate its random, by default it uses a Mersenne Twister. More info in the docs

It uses Mersenne Twister, but (unless I'm reading the code incorrectly) the default seed is generated using `Math.random`:

```
    var MersenneTwister = function (seed) {
        if (seed === undefined) {
            // kept random number same size as time used previously to ensure no unexpected results downstream
            seed = Math.floor(Math.random()*Math.pow(10,13));
        }
        /* Period parameters */
        this.N = 624;
        this.M = 397;
        this.MATRIX_A = 0x9908b0df;   /* constant vector a */
        this.UPPER_MASK = 0x80000000; /* most significant w-r bits */
        this.LOWER_MASK = 0x7fffffff; /* least significant r bits */

        this.mt = new Array(this.N); /* the array for the state vector */
        this.mti = this.N + 1; /* mti==N + 1 means mt[N] is not initialized */

        this.init_genrand(seed);
    };
```
> Second, the rationale for not using any specific crypto library under the hood was that Chance was built to work almost anywhere. It will currently run in practically any Browser or Node.js, in Mongo, in Rhino. I've even had people email me about successfully cross-compiling Chance to Java and other languages.

I was not suggesting that you give up cross-platform compatibility, it's trivial to perform feature detection and fallback to vanilla `Math.random` when desired.  I suggested `crypto` because it is available in all non-end-of-life browsers and Node has supported randomBytes since 2011.  This would be a 20-line commit and wouldn't break compatibility in older environments.

**Comment by oliversalzburg** [comment]
Discussing the entropy of an RNG when you're generating a single integer in a library that is used for dummy data does not seem like time well spent.

**Comment by somejeff** [comment]
99% on the time, I use a fixed integer as a seed because I use Chance to build demo web applications.  When the user returns to the site, or moves from page to page, the get a consistent experience.

That said, if for those times I need random data for testing, I wouldn't mind seeing a crypto solution used.  
@indolering, if you can post here a small example of injecting a better integer into the constructor... Thanks!

**Comment by indolering** [comment]
> if you can post here a small example of injecting a better integer into the constructor... Thanks!

Not sure what the source comments meant by "downstream" or whether I can just pass a string, but here is a simple implementation:

```JavaScript
if(window && window.crypto && window.crypto.getRandomValues){ //browser
  seed = "";
  var ints = new Uint32Array(4);
  for(var i = 0; i < ints.length; i++){
    var int = array[i];
    seed = seed + int.toString('hex');
  }
} else if (GLOBAL && !window){ //node
  crypto = require('crypto');
  var buf = crypto.randomBytes(128);
  seed = buf.toString('hex');
} else {
  seed = Math.floor(Math.random()*Math.pow(10,13));
}
```

You could also wrap it in a try/catch if you are concerned about node/browser-detection.

**Comment by indolering** [comment]
> Discussing the entropy of an RNG when you're generating a single integer in a library that is used for dummy data does not seem like time well spent.

In the end-to-end tests I use at work, the client creates records that are actually saved to a database. Collisions between certain fields could result in a failed test.  To save time, I run several versions of each browser in parallel. Since we aren't using the `crypto` API, it's entirely possible that the browser's seed could remain unchanged due to the limited entropy available on the virtual machines.  I thought of this in advance and use Selenium's test session UUID as a seed, but it would be nice if `chance.js` used a truly random seed by default.  Given the triviality of the change ....

**Comment by oliversalzburg** [comment]
It doesn't matter if it's "truly random", it won't save you from collisions. Random does not imply unique. You're already doing the correct thing by using a unique seed.

**Comment by indolering** [comment]
> It doesn't matter if it's "truly random", it won't save you from collisions. Random does not imply unique. 

Uhh, using a high-entropy source of random is ~half the point of crypto.getRandomValues.

> Random does not imply unique. 

It implies lower chances of collisions and (in many cases) virtually eliminates them.  The other half of this is to ensure that the random seed is random and not screwed up by a VM's low entropy state.

> You're already doing the correct thing by using a unique seed.

It would be nice to not have to worry about this sort of thing.  Would you be against a PR adding this functionality?

**Comment by oliversalzburg** [comment]
So, you're currently using a *universally unique* ID for your seed to avoid collisions and want to exchange that for a high-entropy random value, because that is somehow better?

Adding something, that I consider useless, to a library is something I would be opposed to, yes. But this is not my decision :) I just like to argue about this topic :P

**Comment by indolering** [comment]
> So, you're currently using a universally unique ID for your seed to avoid collisions and want to exchange that for a high-entropy random value, because that is somehow better?

They are equivalent, you can get a duplicate UUID due to crappy seeding of the PRNG.  We could cutout the middle man and just make chance.js actually random.

> Adding something, that I consider useless, to a library is something I would be opposed to, yes. But this is not my decision :) I just like to argue about this topic :P

The [very first item on the website's TODO list](http://chancejs.com/#todo) is making chance.js "truly random" which (AFAIK) means switching to a seed with high-quality entropy.  I'm not suggesting altering the PRNG and the `Math.random()` fallback should eliminate compatibility issues.

@victorquinn what am I missing here?  I could use some help figuring out how to pass in 80-128 bits of entropy, but I could just pass in the floating point number the way you outlined earlier....

**Comment by victorquinn** [comment]
> The very first item on the website's TODO list is making chance.js "truly random" which (AFAIK) means switching to a seed with high-quality entropy. I'm not suggesting altering the PRNG and the Math.random() fallback should eliminate compatibility issues.
> 
> @victorquinn what am I missing here?

My apologies, I should probably update that TODO list.

I wrote that [almost 3 years ago now](https://github.com/victorquinn/chancejs/commit/74cc385384016300b0058142be1972a9a1092376) after I first wrote Chance and tried to find a way to get cross platform _true random_ and basically failed.

However, that turned out to be a blessing in disguise because in failing to get _true random_, I stumbled upon another 2 features:

1. [User supplied source of random](http://chancejs.com/#function)
1. _Repeatable random_, which has been a feature many (including myself) have relied upon since.

Since writing that TODO list, there has been a lot of adoption which is fantastic! (there are now >80k downloads per month and almost a hundred dependent modules according to [npm](https://www.npmjs.com/package/chance))

However, along with that comes the responsibility to no longer introduce potentially breaking changes for no great reason. In my opinion, adding the kind of messy script proposed above just to generate a more random seed is not terribly helpful and has the potential to introduce a lot of breakage.

And it doesn't accomplish all that much. My example in my initial reply to you showed how you could use `window.crypto` for a pure random source for all of the Chance generators in your specific use case. 

What you propose is just getting a "more random" seed which then still feeds into a pseudo-random generator which, in my opinion, is not a change of much utility as it doesn't change much.

If that's what you want, I'd say it makes more sense for you to just invoke Chance as follows:

```js
   var arr = new Uint32Array(1);
   window.crypto.getRandomValues(arr);
   var chance = new Chance(arr[0]);
```

Anyway, this is all a really long-winded way of saying I won't accept a PR with the change suggested above to simply get a more random seed on some platforms.

I'd suggest invoking Chance using one of the methods I suggested above to either use `window.crypto` as a source of true random under the hood or as the source of a more random seed for the Mersenne Twister or forking Chance if adding those 2 or 3 lines in your specific use case is really that big of a deal to you (all hail the glory of open source).

**Comment by indolering** [comment]
> However, that turned out to be a blessing in disguise because in failing to get true random, I stumbled upon another 2 features:
User supplied source of random
Repeatable random, which has been a feature many (including myself) have relied upon since.

Both are killer features, I have both in my homegrown solution, but these are orthogonal issues.

> And it doesn't accomplish all that much.

Low entropy testing environments are honestly one of the few places in which seeds with low entropy can be found.  Sure, tests with side-effects are somewhat rare and users can work around the issue, but it would (as you pointed out three years ago) be nice if Chance handled this on it's own.

> However, along with that comes the responsibility to no longer introduce potentially breaking changes for no great reason. In my opinion, adding the kind of messy script proposed above just to generate a more random seed is not terribly helpful and has the potential to introduce a lot of breakage.

I wrote the above code without much thought, here's a better proposal that [uses an enhanced version of **underscore**'s Node detection](http://www.timetler.com/2012/10/13/environment-detection-in-javascript/) and produces a random integer all wrapped neatly in a try/catch.

```
var seed = fallbackSeed();

try {
  if(typeof window !== 'undefined' && typeof window.crypto !== 'undefined' && typeof window.crypto.getRandomValues === 'function'){ //browser
    var arr = new Uint32Array(1);
    window.crypto.getRandomValues(arr);
    seed = arr[0];
  } else if (typeof exports !== 'undefined' && this.exports !== exports){ //node
    crypto = require('crypto');
    var buf = crypto.randomBytes(4);
    var hex = buf.toString('hex');
    seed = parseInt(hex, 16);
  }
} catch(error) {
  seed = fallbackSeed();
}

//overkill
if(typeof seed !== 'number'){
  seed = fallbackSeed();
}

function fallbackSeed(){
  return Math.floor(Math.random()*Math.pow(10,13));
}

```

Unless someone has deliberately sabotaged the environment in a very specific way, you will get a random seed.

**Comment by vlakoff** [comment]
Just to mention that the [current implementation](https://github.com/chancejs/chancejs/blob/3231d9ea9fe53b52a99d0ed70134730f955e02e5/chance.js#L277) might have a bias.

See [this question on Stack Overflow](https://stackoverflow.com/questions/18230217/javascript-generate-a-random-number-within-a-range-using-crypto-getrandomvalues), where most of the answers use similar codes, then see [this answer](https://stackoverflow.com/questions/18230217/javascript-generate-a-random-number-within-a-range-using-crypto-getrandomvalues/65440696#65440696) that states that these codes have a bias, and thankfully provides a code stated as unbiased.
